<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 8/8/2019
 * Time: 2:27 PM
 */
// $company_logo = asset($model->institute->logo);
?>


<!DOCTYPE html>
<html>

<head>
    {{-- <title>Pos Invoice</title> --}}
    <style type="text/css">
        body {
            margin: 0 auto;
            padding: 0;
            font-family: Verdana;
        }


        /* .fs-10 {
            font-size: 10px;
        }

        .fs-12 {
            font-size: 12px;
        } */

        .border-bottom {
            border-bottom: 2px solid;
        }

        .fw-500 {
            font-weight: 500;
        }

        .table-academic {
            width: 100%;
            margin-bottom: 2px solid !important;
            background-color: transparent;
        }


        .sub_test_table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}


    </style>


</head>

<body>
    <div class="container">
        <center id="top">

            <h2 style=" font-size: 20px; margin: 10px auto!important">{{ $company_name }}</h2>
            <div class="info">
                <table class="table_info">
                    @if(isset($report_head_sub_text))
                        <span> {!! $report_head_sub_text !!}</span> <br>

                    @else
                         <span> {{ $company_address }}</span> <br>
                         <span> {{ $company_city.($company_country ? ", ".$company_country : "") }}</span> <br>

                    @endif
                    <span>Phone : {{ $company_phone }}</span>

                </table>
            </div>
        <!--End Info-->
        </center>

        <div style="padding-bottom: 1rem;">

            <div class="box-body">
                <table id="" class="sub_test_table table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#SL</th>
                            <th>Test Group Title</th>
                            <th>Sub Test Group Title</th>
                            <th>Price</th>
                            <th>Unit</th>
                            <th>Quack Ref Com</th>
                            <th>Ref Val</th>
                            <th>Room No</th>

                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($sub_test_groups as $key => $list)
                            <tr>

                                <td>{{ ++$key }}</td>
                                <td>{{ $list->testGroup? $list->testGroup->title : "" }}({{$list->testGroup?$list->testGroup->specimen->specimen : ""}})</td>
                                <td>{{ $list->title }}</td>
                                <td>{{ $list->price }}</td>
                                <td>{{ $list->unit }}</td>
                                <td>{{ $list->quack_ref_com }}</td>
                                <td>{{ $list->ref_val }}</td>
                                <td>{{ $list->room_no }}</td>

                            </tr>
                        @endforeach

                    </tbody>

                </table>

            </div>


        </div>
        {{-- <div id="footer" style="text-align: left; border-top: 1px solid black; margin-top: 2px;">
            <span style="font-size:7px;">Generated by {{ env('APP_NAME') }} </span><span
                style="font-size:7px;color:blue"> {{ url("") }}</span>

        </div> --}}
    </div>

    <!--End Invoice-->
</body>
<script type="text/javascript">

    window.print();
    window.onafterprint = back;

    // function back() {
    //     window.location.replace(pos_url);
    // }
</script>

</html>
